/*
* generated by Xtext
*/
package migdb.dsl.app.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AppOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
