/*
* generated by Xtext
*/
package migdb.dsl.ops.ui.contentassist;

import migdb.dsl.ops.ui.contentassist.AbstractOpsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class OpsProposalProvider extends AbstractOpsProposalProvider {

}
