/*
 * generated by Xtext
 */
package migdb.dsl.app.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AppUiModule extends migdb.dsl.app.ui.AbstractAppUiModule {
	public AppUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
