/*
 * generated by Xtext
 */
package migdb.dsl.ops.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class OpsUiModule extends migdb.dsl.ops.ui.AbstractOpsUiModule {
	public OpsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
