/*
* generated by Xtext
*/
package migdb.dsl.app.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import migdb.dsl.app.services.AppGrammarAccess;

public class AppParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AppGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected migdb.dsl.app.parser.antlr.internal.InternalAppParser createParser(XtextTokenStream stream) {
		return new migdb.dsl.app.parser.antlr.internal.InternalAppParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ModelRoot";
	}
	
	public AppGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AppGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
