/*
* generated by Xtext
*/
package migdb.dsl.ops.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OpsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("migdb/dsl/ops/parser/antlr/internal/InternalOps.tokens");
	}
}
