/*
* generated by Xtext
*/
package migdb.dsl.ops.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import migdb.dsl.ops.services.OpsGrammarAccess;

public class OpsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private OpsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected migdb.dsl.ops.parser.antlr.internal.InternalOpsParser createParser(XtextTokenStream stream) {
		return new migdb.dsl.ops.parser.antlr.internal.InternalOpsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "ModelRoot";
	}
	
	public OpsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(OpsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
