/*
* generated by Xtext
*/

package migdb.dsl.app.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AppGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelRootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ModelRoot");
		private final RuleCall cStructureParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ModelRoot returns app::ModelRoot:
		//	Structure;
		public ParserRule getRule() { return rule; }

		//Structure
		public RuleCall getStructureParserRuleCall() { return cStructureParserRuleCall; }
	}

	public class StructureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Structure");
		private final Assignment cEntitiesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cEntitiesModelEntityParserRuleCall_0 = (RuleCall)cEntitiesAssignment.eContents().get(0);
		
		//Structure returns app::Structure:
		//	entities+=ModelEntity*;
		public ParserRule getRule() { return rule; }

		//entities+=ModelEntity*
		public Assignment getEntitiesAssignment() { return cEntitiesAssignment; }

		//ModelEntity
		public RuleCall getEntitiesModelEntityParserRuleCall_0() { return cEntitiesModelEntityParserRuleCall_0; }
	}

	public class ModelEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ModelEntity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cGeneralClassParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPrimitiveClassParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//ModelEntity returns app::ModelEntity:
		//	GeneralClass | PrimitiveClass;
		public ParserRule getRule() { return rule; }

		//GeneralClass | PrimitiveClass
		public Alternatives getAlternatives() { return cAlternatives; }

		//GeneralClass
		public RuleCall getGeneralClassParserRuleCall_0() { return cGeneralClassParserRuleCall_0; }

		//PrimitiveClass
		public RuleCall getPrimitiveClassParserRuleCall_1() { return cPrimitiveClassParserRuleCall_1; }
	}

	public class GeneralClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GeneralClass");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEmbeddedClassParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStandardClassParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//GeneralClass returns app::GeneralClass:
		//	EmbeddedClass | StandardClass;
		public ParserRule getRule() { return rule; }

		//EmbeddedClass | StandardClass
		public Alternatives getAlternatives() { return cAlternatives; }

		//EmbeddedClass
		public RuleCall getEmbeddedClassParserRuleCall_0() { return cEmbeddedClassParserRuleCall_0; }

		//StandardClass
		public RuleCall getStandardClassParserRuleCall_1() { return cStandardClassParserRuleCall_1; }
	}

	public class PrimitiveClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimitiveClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrimitiveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPrimitiveTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPrimitiveTypePrimitiveTypeEnumRuleCall_3_0 = (RuleCall)cPrimitiveTypeAssignment_3.eContents().get(0);
		
		//PrimitiveClass returns app::PrimitiveClass:
		//	"primitive" name=ID ":" primitiveType=PrimitiveType;
		public ParserRule getRule() { return rule; }

		//"primitive" name=ID ":" primitiveType=PrimitiveType
		public Group getGroup() { return cGroup; }

		//"primitive"
		public Keyword getPrimitiveKeyword_0() { return cPrimitiveKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//primitiveType=PrimitiveType
		public Assignment getPrimitiveTypeAssignment_3() { return cPrimitiveTypeAssignment_3; }

		//PrimitiveType
		public RuleCall getPrimitiveTypePrimitiveTypeEnumRuleCall_3_0() { return cPrimitiveTypePrimitiveTypeEnumRuleCall_3_0; }
	}

	public class EmbeddedClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EmbeddedClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEmbeddedKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIdKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cIdPropertyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cIdPropertyEmbeddedPropertyCrossReference_4_0 = (CrossReference)cIdPropertyAssignment_4.eContents().get(0);
		private final RuleCall cIdPropertyEmbeddedPropertyIDTerminalRuleCall_4_0_1 = (RuleCall)cIdPropertyEmbeddedPropertyCrossReference_4_0.eContents().get(1);
		private final Assignment cEmbeddedPropertiesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cEmbeddedPropertiesEmbeddedPropertyCrossReference_5_0 = (CrossReference)cEmbeddedPropertiesAssignment_5.eContents().get(0);
		private final RuleCall cEmbeddedPropertiesEmbeddedPropertyIDTerminalRuleCall_5_0_1 = (RuleCall)cEmbeddedPropertiesEmbeddedPropertyCrossReference_5_0.eContents().get(1);
		private final Assignment cEmbeddedPropertiesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cEmbeddedPropertiesEmbeddedPropertyCrossReference_6_0 = (CrossReference)cEmbeddedPropertiesAssignment_6.eContents().get(0);
		private final RuleCall cEmbeddedPropertiesEmbeddedPropertyIDTerminalRuleCall_6_0_1 = (RuleCall)cEmbeddedPropertiesEmbeddedPropertyCrossReference_6_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		/// **
		// * descendants of GeneralClass
		// * / EmbeddedClass returns app::EmbeddedClass:
		//	"embedded" name=ID "{" "id" idProperty= //FIXME: reference???
		//	[app::EmbeddedProperty] embeddedProperties+=[app::EmbeddedProperty] embeddedProperties+=[app::EmbeddedProperty]* //FIXME: reference???
		//	"}";
		public ParserRule getRule() { return rule; }

		//"embedded" name=ID "{" "id" idProperty= //FIXME: reference???
		//[app::EmbeddedProperty] embeddedProperties+=[app::EmbeddedProperty] embeddedProperties+=[app::EmbeddedProperty]* //FIXME: reference???
		//"}"
		public Group getGroup() { return cGroup; }

		//"embedded"
		public Keyword getEmbeddedKeyword_0() { return cEmbeddedKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"id"
		public Keyword getIdKeyword_3() { return cIdKeyword_3; }

		//idProperty= //FIXME: reference???
		//[app::EmbeddedProperty]
		public Assignment getIdPropertyAssignment_4() { return cIdPropertyAssignment_4; }

		////FIXME: reference???
		//[app::EmbeddedProperty]
		public CrossReference getIdPropertyEmbeddedPropertyCrossReference_4_0() { return cIdPropertyEmbeddedPropertyCrossReference_4_0; }

		//ID
		public RuleCall getIdPropertyEmbeddedPropertyIDTerminalRuleCall_4_0_1() { return cIdPropertyEmbeddedPropertyIDTerminalRuleCall_4_0_1; }

		//embeddedProperties+=[app::EmbeddedProperty]
		public Assignment getEmbeddedPropertiesAssignment_5() { return cEmbeddedPropertiesAssignment_5; }

		//[app::EmbeddedProperty]
		public CrossReference getEmbeddedPropertiesEmbeddedPropertyCrossReference_5_0() { return cEmbeddedPropertiesEmbeddedPropertyCrossReference_5_0; }

		//ID
		public RuleCall getEmbeddedPropertiesEmbeddedPropertyIDTerminalRuleCall_5_0_1() { return cEmbeddedPropertiesEmbeddedPropertyIDTerminalRuleCall_5_0_1; }

		//embeddedProperties+=[app::EmbeddedProperty]*
		public Assignment getEmbeddedPropertiesAssignment_6() { return cEmbeddedPropertiesAssignment_6; }

		//[app::EmbeddedProperty]
		public CrossReference getEmbeddedPropertiesEmbeddedPropertyCrossReference_6_0() { return cEmbeddedPropertiesEmbeddedPropertyCrossReference_6_0; }

		//ID
		public RuleCall getEmbeddedPropertiesEmbeddedPropertyIDTerminalRuleCall_6_0_1() { return cEmbeddedPropertiesEmbeddedPropertyIDTerminalRuleCall_6_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class StandardClassElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StandardClass");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsAbstractAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsAbstractAbstractKeyword_0_0 = (Keyword)cIsAbstractAssignment_0.eContents().get(0);
		private final Keyword cClassKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cExtendsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cParentAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final CrossReference cParentStandardClassCrossReference_3_1_0 = (CrossReference)cParentAssignment_3_1.eContents().get(0);
		private final RuleCall cParentStandardClassIDTerminalRuleCall_3_1_0_1 = (RuleCall)cParentStandardClassCrossReference_3_1_0.eContents().get(1);
		private final Keyword cByKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Assignment cInheritanceTypeAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cInheritanceTypeInheritanceTypeEnumRuleCall_3_3_0 = (RuleCall)cInheritanceTypeAssignment_3_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cIdKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cIdPropertyAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cIdPropertyPrimitivePropertyCrossReference_5_1_0 = (CrossReference)cIdPropertyAssignment_5_1.eContents().get(0);
		private final RuleCall cIdPropertyPrimitivePropertyIDTerminalRuleCall_5_1_0_1 = (RuleCall)cIdPropertyPrimitivePropertyCrossReference_5_1_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Assignment cPropertiesAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final RuleCall cPropertiesMultipliablePropertyParserRuleCall_6_0_0 = (RuleCall)cPropertiesAssignment_6_0.eContents().get(0);
		private final Assignment cPropertiesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPropertiesMultipliablePropertyParserRuleCall_6_1_0 = (RuleCall)cPropertiesAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//StandardClass returns app::StandardClass:
		//	isAbstract?="abstract"? "class" name=ID ("extends" parent=[app::StandardClass] "by" inheritanceType=InheritanceType)?
		//	"{" ("id" idProperty=[app::PrimitiveProperty])? //FIXME: reference???
		//	(properties+=MultipliableProperty properties+=MultipliableProperty*)? "}";
		public ParserRule getRule() { return rule; }

		//isAbstract?="abstract"? "class" name=ID ("extends" parent=[app::StandardClass] "by" inheritanceType=InheritanceType)?
		//"{" ("id" idProperty=[app::PrimitiveProperty])? //FIXME: reference???
		//(properties+=MultipliableProperty properties+=MultipliableProperty*)? "}"
		public Group getGroup() { return cGroup; }

		//isAbstract?="abstract"?
		public Assignment getIsAbstractAssignment_0() { return cIsAbstractAssignment_0; }

		//"abstract"
		public Keyword getIsAbstractAbstractKeyword_0_0() { return cIsAbstractAbstractKeyword_0_0; }

		//"class"
		public Keyword getClassKeyword_1() { return cClassKeyword_1; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//("extends" parent=[app::StandardClass] "by" inheritanceType=InheritanceType)?
		public Group getGroup_3() { return cGroup_3; }

		//"extends"
		public Keyword getExtendsKeyword_3_0() { return cExtendsKeyword_3_0; }

		//parent=[app::StandardClass]
		public Assignment getParentAssignment_3_1() { return cParentAssignment_3_1; }

		//[app::StandardClass]
		public CrossReference getParentStandardClassCrossReference_3_1_0() { return cParentStandardClassCrossReference_3_1_0; }

		//ID
		public RuleCall getParentStandardClassIDTerminalRuleCall_3_1_0_1() { return cParentStandardClassIDTerminalRuleCall_3_1_0_1; }

		//"by"
		public Keyword getByKeyword_3_2() { return cByKeyword_3_2; }

		//inheritanceType=InheritanceType
		public Assignment getInheritanceTypeAssignment_3_3() { return cInheritanceTypeAssignment_3_3; }

		//InheritanceType
		public RuleCall getInheritanceTypeInheritanceTypeEnumRuleCall_3_3_0() { return cInheritanceTypeInheritanceTypeEnumRuleCall_3_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }

		//("id" idProperty=[app::PrimitiveProperty])?
		public Group getGroup_5() { return cGroup_5; }

		//"id"
		public Keyword getIdKeyword_5_0() { return cIdKeyword_5_0; }

		//idProperty=[app::PrimitiveProperty]
		public Assignment getIdPropertyAssignment_5_1() { return cIdPropertyAssignment_5_1; }

		//[app::PrimitiveProperty]
		public CrossReference getIdPropertyPrimitivePropertyCrossReference_5_1_0() { return cIdPropertyPrimitivePropertyCrossReference_5_1_0; }

		//ID
		public RuleCall getIdPropertyPrimitivePropertyIDTerminalRuleCall_5_1_0_1() { return cIdPropertyPrimitivePropertyIDTerminalRuleCall_5_1_0_1; }

		//(properties+=MultipliableProperty properties+=MultipliableProperty*)?
		public Group getGroup_6() { return cGroup_6; }

		//properties+=MultipliableProperty
		public Assignment getPropertiesAssignment_6_0() { return cPropertiesAssignment_6_0; }

		//MultipliableProperty
		public RuleCall getPropertiesMultipliablePropertyParserRuleCall_6_0_0() { return cPropertiesMultipliablePropertyParserRuleCall_6_0_0; }

		//properties+=MultipliableProperty*
		public Assignment getPropertiesAssignment_6_1() { return cPropertiesAssignment_6_1; }

		//MultipliableProperty
		public RuleCall getPropertiesMultipliablePropertyParserRuleCall_6_1_0() { return cPropertiesMultipliablePropertyParserRuleCall_6_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class PropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Property");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMultipliablePropertyParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEmbeddedPropertyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Property returns app::Property:
		//	MultipliableProperty | EmbeddedProperty;
		public ParserRule getRule() { return rule; }

		//MultipliableProperty | EmbeddedProperty
		public Alternatives getAlternatives() { return cAlternatives; }

		//MultipliableProperty
		public RuleCall getMultipliablePropertyParserRuleCall_0() { return cMultipliablePropertyParserRuleCall_0; }

		//EmbeddedProperty
		public RuleCall getEmbeddedPropertyParserRuleCall_1() { return cEmbeddedPropertyParserRuleCall_1; }
	}

	public class MultipliablePropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MultipliableProperty");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAssociationPropertyParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPrimitivePropertyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNestedPropertyParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//MultipliableProperty returns app::MultipliableProperty:
		//	AssociationProperty | PrimitiveProperty | NestedProperty;
		public ParserRule getRule() { return rule; }

		//AssociationProperty | PrimitiveProperty | NestedProperty
		public Alternatives getAlternatives() { return cAlternatives; }

		//AssociationProperty
		public RuleCall getAssociationPropertyParserRuleCall_0() { return cAssociationPropertyParserRuleCall_0; }

		//PrimitiveProperty
		public RuleCall getPrimitivePropertyParserRuleCall_1() { return cPrimitivePropertyParserRuleCall_1; }

		//NestedProperty
		public RuleCall getNestedPropertyParserRuleCall_2() { return cNestedPropertyParserRuleCall_2; }
	}

	public class EmbeddedPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EmbeddedProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEmbeddedPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIsMandatoryAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cIsMandatoryMandatoryKeyword_1_0 = (Keyword)cIsMandatoryAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cTypeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cTypePrimitiveClassCrossReference_4_0 = (CrossReference)cTypeAssignment_4.eContents().get(0);
		private final RuleCall cTypePrimitiveClassIDTerminalRuleCall_4_0_1 = (RuleCall)cTypePrimitiveClassCrossReference_4_0.eContents().get(1);
		
		//EmbeddedProperty returns app::EmbeddedProperty:
		//	"EmbeddedProperty" isMandatory?="mandatory" name=ID ":" type=[app::PrimitiveClass];
		public ParserRule getRule() { return rule; }

		//"EmbeddedProperty" isMandatory?="mandatory" name=ID ":" type=[app::PrimitiveClass]
		public Group getGroup() { return cGroup; }

		//"EmbeddedProperty"
		public Keyword getEmbeddedPropertyKeyword_0() { return cEmbeddedPropertyKeyword_0; }

		//isMandatory?="mandatory"
		public Assignment getIsMandatoryAssignment_1() { return cIsMandatoryAssignment_1; }

		//"mandatory"
		public Keyword getIsMandatoryMandatoryKeyword_1_0() { return cIsMandatoryMandatoryKeyword_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//":"
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }

		//type=[app::PrimitiveClass]
		public Assignment getTypeAssignment_4() { return cTypeAssignment_4; }

		//[app::PrimitiveClass]
		public CrossReference getTypePrimitiveClassCrossReference_4_0() { return cTypePrimitiveClassCrossReference_4_0; }

		//ID
		public RuleCall getTypePrimitiveClassIDTerminalRuleCall_4_0_1() { return cTypePrimitiveClassIDTerminalRuleCall_4_0_1; }
	}

	public class PrimitivePropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PrimitiveProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrimitivePropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Assignment cIsOrderedAssignment_1_0 = (Assignment)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cIsOrderedOrderedKeyword_1_0_0 = (Keyword)cIsOrderedAssignment_1_0.eContents().get(0);
		private final Assignment cIsUniqueAssignment_1_1 = (Assignment)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cIsUniqueUniqueKeyword_1_1_0 = (Keyword)cIsUniqueAssignment_1_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Assignment cUpperBoundAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cUpperBoundINTTerminalRuleCall_3_0_1_0 = (RuleCall)cUpperBoundAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Group cGroup_3_1_0 = (Group)cGroup_3_1.eContents().get(0);
		private final Assignment cLowerBoundAssignment_3_1_0_0 = (Assignment)cGroup_3_1_0.eContents().get(0);
		private final RuleCall cLowerBoundINTTerminalRuleCall_3_1_0_0_0 = (RuleCall)cLowerBoundAssignment_3_1_0_0.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_3_1_0_1 = (Keyword)cGroup_3_1_0.eContents().get(1);
		private final Assignment cUpperBoundAssignment_3_1_0_2 = (Assignment)cGroup_3_1_0.eContents().get(2);
		private final RuleCall cUpperBoundINTTerminalRuleCall_3_1_0_2_0 = (RuleCall)cUpperBoundAssignment_3_1_0_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cTypePrimitiveClassCrossReference_5_0 = (CrossReference)cTypeAssignment_5.eContents().get(0);
		private final RuleCall cTypePrimitiveClassIDTerminalRuleCall_5_0_1 = (RuleCall)cTypePrimitiveClassCrossReference_5_0.eContents().get(1);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cEqualsSignKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cDefaultValueAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cDefaultValueIDTerminalRuleCall_6_1_0 = (RuleCall)cDefaultValueAssignment_6_1.eContents().get(0);
		
		//PrimitiveProperty returns app::PrimitiveProperty:
		//	"PrimitiveProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
		//	upperBound=INT) "]")? ":" type=[app::PrimitiveClass] ("=" defaultValue=ID)?;
		public ParserRule getRule() { return rule; }

		//"PrimitiveProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
		//upperBound=INT) "]")? ":" type=[app::PrimitiveClass] ("=" defaultValue=ID)?
		public Group getGroup() { return cGroup; }

		//"PrimitiveProperty"
		public Keyword getPrimitivePropertyKeyword_0() { return cPrimitivePropertyKeyword_0; }

		//isOrdered?="ordered"? & isUnique?="unique"?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//isOrdered?="ordered"?
		public Assignment getIsOrderedAssignment_1_0() { return cIsOrderedAssignment_1_0; }

		//"ordered"
		public Keyword getIsOrderedOrderedKeyword_1_0_0() { return cIsOrderedOrderedKeyword_1_0_0; }

		//isUnique?="unique"?
		public Assignment getIsUniqueAssignment_1_1() { return cIsUniqueAssignment_1_1; }

		//"unique"
		public Keyword getIsUniqueUniqueKeyword_1_1_0() { return cIsUniqueUniqueKeyword_1_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//("[" upperBound=INT | (lowerBound=INT ".." upperBound=INT) "]")?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//"[" upperBound=INT
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3_0_0() { return cLeftSquareBracketKeyword_3_0_0; }

		//upperBound=INT
		public Assignment getUpperBoundAssignment_3_0_1() { return cUpperBoundAssignment_3_0_1; }

		//INT
		public RuleCall getUpperBoundINTTerminalRuleCall_3_0_1_0() { return cUpperBoundINTTerminalRuleCall_3_0_1_0; }

		//(lowerBound=INT ".." upperBound=INT) "]"
		public Group getGroup_3_1() { return cGroup_3_1; }

		//lowerBound=INT ".." upperBound=INT
		public Group getGroup_3_1_0() { return cGroup_3_1_0; }

		//lowerBound=INT
		public Assignment getLowerBoundAssignment_3_1_0_0() { return cLowerBoundAssignment_3_1_0_0; }

		//INT
		public RuleCall getLowerBoundINTTerminalRuleCall_3_1_0_0_0() { return cLowerBoundINTTerminalRuleCall_3_1_0_0_0; }

		//".."
		public Keyword getFullStopFullStopKeyword_3_1_0_1() { return cFullStopFullStopKeyword_3_1_0_1; }

		//upperBound=INT
		public Assignment getUpperBoundAssignment_3_1_0_2() { return cUpperBoundAssignment_3_1_0_2; }

		//INT
		public RuleCall getUpperBoundINTTerminalRuleCall_3_1_0_2_0() { return cUpperBoundINTTerminalRuleCall_3_1_0_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3_1_1() { return cRightSquareBracketKeyword_3_1_1; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//type=[app::PrimitiveClass]
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }

		//[app::PrimitiveClass]
		public CrossReference getTypePrimitiveClassCrossReference_5_0() { return cTypePrimitiveClassCrossReference_5_0; }

		//ID
		public RuleCall getTypePrimitiveClassIDTerminalRuleCall_5_0_1() { return cTypePrimitiveClassIDTerminalRuleCall_5_0_1; }

		//("=" defaultValue=ID)?
		public Group getGroup_6() { return cGroup_6; }

		//"="
		public Keyword getEqualsSignKeyword_6_0() { return cEqualsSignKeyword_6_0; }

		//defaultValue=ID
		public Assignment getDefaultValueAssignment_6_1() { return cDefaultValueAssignment_6_1; }

		//ID
		public RuleCall getDefaultValueIDTerminalRuleCall_6_1_0() { return cDefaultValueIDTerminalRuleCall_6_1_0; }
	}

	public class AssociationPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AssociationProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssociationPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Assignment cIsOrderedAssignment_1_0 = (Assignment)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cIsOrderedOrderedKeyword_1_0_0 = (Keyword)cIsOrderedAssignment_1_0.eContents().get(0);
		private final Assignment cIsUniqueAssignment_1_1 = (Assignment)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cIsUniqueUniqueKeyword_1_1_0 = (Keyword)cIsUniqueAssignment_1_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Assignment cUpperBoundAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cUpperBoundINTTerminalRuleCall_3_0_1_0 = (RuleCall)cUpperBoundAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Group cGroup_3_1_0 = (Group)cGroup_3_1.eContents().get(0);
		private final Assignment cLowerBoundAssignment_3_1_0_0 = (Assignment)cGroup_3_1_0.eContents().get(0);
		private final RuleCall cLowerBoundINTTerminalRuleCall_3_1_0_0_0 = (RuleCall)cLowerBoundAssignment_3_1_0_0.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_3_1_0_1 = (Keyword)cGroup_3_1_0.eContents().get(1);
		private final Assignment cUpperBoundAssignment_3_1_0_2 = (Assignment)cGroup_3_1_0.eContents().get(2);
		private final RuleCall cUpperBoundINTTerminalRuleCall_3_1_0_2_0 = (RuleCall)cUpperBoundAssignment_3_1_0_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOpositeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOppositePropertyAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cOppositePropertyAssociationPropertyCrossReference_4_1_0 = (CrossReference)cOppositePropertyAssignment_4_1.eContents().get(0);
		private final RuleCall cOppositePropertyAssociationPropertyIDTerminalRuleCall_4_1_0_1 = (RuleCall)cOppositePropertyAssociationPropertyCrossReference_4_1_0.eContents().get(1);
		private final Keyword cColonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTypeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cTypeStandardClassCrossReference_6_0 = (CrossReference)cTypeAssignment_6.eContents().get(0);
		private final RuleCall cTypeStandardClassIDTerminalRuleCall_6_0_1 = (RuleCall)cTypeStandardClassCrossReference_6_0.eContents().get(1);
		
		//AssociationProperty returns app::AssociationProperty:
		//	"AssociationProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
		//	upperBound=INT) "]")? ("oposite" oppositeProperty=[app::AssociationProperty])? ":" type=[app::StandardClass];
		public ParserRule getRule() { return rule; }

		//"AssociationProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
		//upperBound=INT) "]")? ("oposite" oppositeProperty=[app::AssociationProperty])? ":" type=[app::StandardClass]
		public Group getGroup() { return cGroup; }

		//"AssociationProperty"
		public Keyword getAssociationPropertyKeyword_0() { return cAssociationPropertyKeyword_0; }

		//isOrdered?="ordered"? & isUnique?="unique"?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//isOrdered?="ordered"?
		public Assignment getIsOrderedAssignment_1_0() { return cIsOrderedAssignment_1_0; }

		//"ordered"
		public Keyword getIsOrderedOrderedKeyword_1_0_0() { return cIsOrderedOrderedKeyword_1_0_0; }

		//isUnique?="unique"?
		public Assignment getIsUniqueAssignment_1_1() { return cIsUniqueAssignment_1_1; }

		//"unique"
		public Keyword getIsUniqueUniqueKeyword_1_1_0() { return cIsUniqueUniqueKeyword_1_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//("[" upperBound=INT | (lowerBound=INT ".." upperBound=INT) "]")?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//"[" upperBound=INT
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3_0_0() { return cLeftSquareBracketKeyword_3_0_0; }

		//upperBound=INT
		public Assignment getUpperBoundAssignment_3_0_1() { return cUpperBoundAssignment_3_0_1; }

		//INT
		public RuleCall getUpperBoundINTTerminalRuleCall_3_0_1_0() { return cUpperBoundINTTerminalRuleCall_3_0_1_0; }

		//(lowerBound=INT ".." upperBound=INT) "]"
		public Group getGroup_3_1() { return cGroup_3_1; }

		//lowerBound=INT ".." upperBound=INT
		public Group getGroup_3_1_0() { return cGroup_3_1_0; }

		//lowerBound=INT
		public Assignment getLowerBoundAssignment_3_1_0_0() { return cLowerBoundAssignment_3_1_0_0; }

		//INT
		public RuleCall getLowerBoundINTTerminalRuleCall_3_1_0_0_0() { return cLowerBoundINTTerminalRuleCall_3_1_0_0_0; }

		//".."
		public Keyword getFullStopFullStopKeyword_3_1_0_1() { return cFullStopFullStopKeyword_3_1_0_1; }

		//upperBound=INT
		public Assignment getUpperBoundAssignment_3_1_0_2() { return cUpperBoundAssignment_3_1_0_2; }

		//INT
		public RuleCall getUpperBoundINTTerminalRuleCall_3_1_0_2_0() { return cUpperBoundINTTerminalRuleCall_3_1_0_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3_1_1() { return cRightSquareBracketKeyword_3_1_1; }

		//("oposite" oppositeProperty=[app::AssociationProperty])?
		public Group getGroup_4() { return cGroup_4; }

		//"oposite"
		public Keyword getOpositeKeyword_4_0() { return cOpositeKeyword_4_0; }

		//oppositeProperty=[app::AssociationProperty]
		public Assignment getOppositePropertyAssignment_4_1() { return cOppositePropertyAssignment_4_1; }

		//[app::AssociationProperty]
		public CrossReference getOppositePropertyAssociationPropertyCrossReference_4_1_0() { return cOppositePropertyAssociationPropertyCrossReference_4_1_0; }

		//ID
		public RuleCall getOppositePropertyAssociationPropertyIDTerminalRuleCall_4_1_0_1() { return cOppositePropertyAssociationPropertyIDTerminalRuleCall_4_1_0_1; }

		//":"
		public Keyword getColonKeyword_5() { return cColonKeyword_5; }

		//type=[app::StandardClass]
		public Assignment getTypeAssignment_6() { return cTypeAssignment_6; }

		//[app::StandardClass]
		public CrossReference getTypeStandardClassCrossReference_6_0() { return cTypeStandardClassCrossReference_6_0; }

		//ID
		public RuleCall getTypeStandardClassIDTerminalRuleCall_6_0_1() { return cTypeStandardClassIDTerminalRuleCall_6_0_1; }
	}

	public class NestedPropertyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NestedProperty");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNestedPropertyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Assignment cIsOrderedAssignment_1_0 = (Assignment)cUnorderedGroup_1.eContents().get(0);
		private final Keyword cIsOrderedOrderedKeyword_1_0_0 = (Keyword)cIsOrderedAssignment_1_0.eContents().get(0);
		private final Assignment cIsUniqueAssignment_1_1 = (Assignment)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cIsUniqueUniqueKeyword_1_1_0 = (Keyword)cIsUniqueAssignment_1_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Group cGroup_3_0 = (Group)cAlternatives_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3_0_0 = (Keyword)cGroup_3_0.eContents().get(0);
		private final Assignment cUpperBoundAssignment_3_0_1 = (Assignment)cGroup_3_0.eContents().get(1);
		private final RuleCall cUpperBoundINTTerminalRuleCall_3_0_1_0 = (RuleCall)cUpperBoundAssignment_3_0_1.eContents().get(0);
		private final Group cGroup_3_1 = (Group)cAlternatives_3.eContents().get(1);
		private final Group cGroup_3_1_0 = (Group)cGroup_3_1.eContents().get(0);
		private final Assignment cLowerBoundAssignment_3_1_0_0 = (Assignment)cGroup_3_1_0.eContents().get(0);
		private final RuleCall cLowerBoundINTTerminalRuleCall_3_1_0_0_0 = (RuleCall)cLowerBoundAssignment_3_1_0_0.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_3_1_0_1 = (Keyword)cGroup_3_1_0.eContents().get(1);
		private final Assignment cUpperBoundAssignment_3_1_0_2 = (Assignment)cGroup_3_1_0.eContents().get(2);
		private final RuleCall cUpperBoundINTTerminalRuleCall_3_1_0_2_0 = (RuleCall)cUpperBoundAssignment_3_1_0_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_1_1 = (Keyword)cGroup_3_1.eContents().get(1);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTypeAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cTypeEmbeddedClassCrossReference_5_0 = (CrossReference)cTypeAssignment_5.eContents().get(0);
		private final RuleCall cTypeEmbeddedClassIDTerminalRuleCall_5_0_1 = (RuleCall)cTypeEmbeddedClassCrossReference_5_0.eContents().get(1);
		
		//NestedProperty returns app::NestedProperty:
		//	"NestedProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
		//	upperBound=INT) "]")? ":" type=[app::EmbeddedClass];
		public ParserRule getRule() { return rule; }

		//"NestedProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
		//upperBound=INT) "]")? ":" type=[app::EmbeddedClass]
		public Group getGroup() { return cGroup; }

		//"NestedProperty"
		public Keyword getNestedPropertyKeyword_0() { return cNestedPropertyKeyword_0; }

		//isOrdered?="ordered"? & isUnique?="unique"?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }

		//isOrdered?="ordered"?
		public Assignment getIsOrderedAssignment_1_0() { return cIsOrderedAssignment_1_0; }

		//"ordered"
		public Keyword getIsOrderedOrderedKeyword_1_0_0() { return cIsOrderedOrderedKeyword_1_0_0; }

		//isUnique?="unique"?
		public Assignment getIsUniqueAssignment_1_1() { return cIsUniqueAssignment_1_1; }

		//"unique"
		public Keyword getIsUniqueUniqueKeyword_1_1_0() { return cIsUniqueUniqueKeyword_1_1_0; }

		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }

		//("[" upperBound=INT | (lowerBound=INT ".." upperBound=INT) "]")?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//"[" upperBound=INT
		public Group getGroup_3_0() { return cGroup_3_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_3_0_0() { return cLeftSquareBracketKeyword_3_0_0; }

		//upperBound=INT
		public Assignment getUpperBoundAssignment_3_0_1() { return cUpperBoundAssignment_3_0_1; }

		//INT
		public RuleCall getUpperBoundINTTerminalRuleCall_3_0_1_0() { return cUpperBoundINTTerminalRuleCall_3_0_1_0; }

		//(lowerBound=INT ".." upperBound=INT) "]"
		public Group getGroup_3_1() { return cGroup_3_1; }

		//lowerBound=INT ".." upperBound=INT
		public Group getGroup_3_1_0() { return cGroup_3_1_0; }

		//lowerBound=INT
		public Assignment getLowerBoundAssignment_3_1_0_0() { return cLowerBoundAssignment_3_1_0_0; }

		//INT
		public RuleCall getLowerBoundINTTerminalRuleCall_3_1_0_0_0() { return cLowerBoundINTTerminalRuleCall_3_1_0_0_0; }

		//".."
		public Keyword getFullStopFullStopKeyword_3_1_0_1() { return cFullStopFullStopKeyword_3_1_0_1; }

		//upperBound=INT
		public Assignment getUpperBoundAssignment_3_1_0_2() { return cUpperBoundAssignment_3_1_0_2; }

		//INT
		public RuleCall getUpperBoundINTTerminalRuleCall_3_1_0_2_0() { return cUpperBoundINTTerminalRuleCall_3_1_0_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3_1_1() { return cRightSquareBracketKeyword_3_1_1; }

		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }

		//type=[app::EmbeddedClass]
		public Assignment getTypeAssignment_5() { return cTypeAssignment_5; }

		//[app::EmbeddedClass]
		public CrossReference getTypeEmbeddedClassCrossReference_5_0() { return cTypeEmbeddedClassCrossReference_5_0; }

		//ID
		public RuleCall getTypeEmbeddedClassIDTerminalRuleCall_5_0_1() { return cTypeEmbeddedClassIDTerminalRuleCall_5_0_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	
	
	public class PrimitiveTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "PrimitiveType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBooleanBooleanKeyword_0_0 = (Keyword)cBooleanEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCharEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCharCharKeyword_1_0 = (Keyword)cCharEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cIntIntKeyword_2_0 = (Keyword)cIntEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum PrimitiveType returns app::PrimitiveType:
		//	boolean | char | int;
		public EnumRule getRule() { return rule; }

		//boolean | char | int
		public Alternatives getAlternatives() { return cAlternatives; }

		//boolean
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_0() { return cBooleanEnumLiteralDeclaration_0; }

		//"boolean"
		public Keyword getBooleanBooleanKeyword_0_0() { return cBooleanBooleanKeyword_0_0; }

		//char
		public EnumLiteralDeclaration getCharEnumLiteralDeclaration_1() { return cCharEnumLiteralDeclaration_1; }

		//"char"
		public Keyword getCharCharKeyword_1_0() { return cCharCharKeyword_1_0; }

		//int
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_2() { return cIntEnumLiteralDeclaration_2; }

		//"int"
		public Keyword getIntIntKeyword_2_0() { return cIntIntKeyword_2_0; }
	}

	public class InheritanceTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "InheritanceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cJoinedEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cJoinedJoinedKeyword_0_0 = (Keyword)cJoinedEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTablePerClassEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTablePerClassTablePerClassKeyword_1_0 = (Keyword)cTablePerClassEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cSingleTableEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cSingleTableSingleTableKeyword_2_0 = (Keyword)cSingleTableEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum InheritanceType returns app::InheritanceType:
		//	joined | tablePerClass | singleTable;
		public EnumRule getRule() { return rule; }

		//joined | tablePerClass | singleTable
		public Alternatives getAlternatives() { return cAlternatives; }

		//joined
		public EnumLiteralDeclaration getJoinedEnumLiteralDeclaration_0() { return cJoinedEnumLiteralDeclaration_0; }

		//"joined"
		public Keyword getJoinedJoinedKeyword_0_0() { return cJoinedJoinedKeyword_0_0; }

		//tablePerClass
		public EnumLiteralDeclaration getTablePerClassEnumLiteralDeclaration_1() { return cTablePerClassEnumLiteralDeclaration_1; }

		//"tablePerClass"
		public Keyword getTablePerClassTablePerClassKeyword_1_0() { return cTablePerClassTablePerClassKeyword_1_0; }

		//singleTable
		public EnumLiteralDeclaration getSingleTableEnumLiteralDeclaration_2() { return cSingleTableEnumLiteralDeclaration_2; }

		//"singleTable"
		public Keyword getSingleTableSingleTableKeyword_2_0() { return cSingleTableSingleTableKeyword_2_0; }
	}
	
	private ModelRootElements pModelRoot;
	private StructureElements pStructure;
	private ModelEntityElements pModelEntity;
	private GeneralClassElements pGeneralClass;
	private PrimitiveClassElements pPrimitiveClass;
	private EmbeddedClassElements pEmbeddedClass;
	private StandardClassElements pStandardClass;
	private PropertyElements pProperty;
	private MultipliablePropertyElements pMultipliableProperty;
	private EmbeddedPropertyElements pEmbeddedProperty;
	private PrimitivePropertyElements pPrimitiveProperty;
	private AssociationPropertyElements pAssociationProperty;
	private NestedPropertyElements pNestedProperty;
	private PrimitiveTypeElements unknownRulePrimitiveType;
	private InheritanceTypeElements unknownRuleInheritanceType;
	private EBooleanElements pEBoolean;
	private TerminalRule tID;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public AppGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//ModelRoot returns app::ModelRoot:
	//	Structure;
	public ModelRootElements getModelRootAccess() {
		return (pModelRoot != null) ? pModelRoot : (pModelRoot = new ModelRootElements());
	}
	
	public ParserRule getModelRootRule() {
		return getModelRootAccess().getRule();
	}

	//Structure returns app::Structure:
	//	entities+=ModelEntity*;
	public StructureElements getStructureAccess() {
		return (pStructure != null) ? pStructure : (pStructure = new StructureElements());
	}
	
	public ParserRule getStructureRule() {
		return getStructureAccess().getRule();
	}

	//ModelEntity returns app::ModelEntity:
	//	GeneralClass | PrimitiveClass;
	public ModelEntityElements getModelEntityAccess() {
		return (pModelEntity != null) ? pModelEntity : (pModelEntity = new ModelEntityElements());
	}
	
	public ParserRule getModelEntityRule() {
		return getModelEntityAccess().getRule();
	}

	//GeneralClass returns app::GeneralClass:
	//	EmbeddedClass | StandardClass;
	public GeneralClassElements getGeneralClassAccess() {
		return (pGeneralClass != null) ? pGeneralClass : (pGeneralClass = new GeneralClassElements());
	}
	
	public ParserRule getGeneralClassRule() {
		return getGeneralClassAccess().getRule();
	}

	//PrimitiveClass returns app::PrimitiveClass:
	//	"primitive" name=ID ":" primitiveType=PrimitiveType;
	public PrimitiveClassElements getPrimitiveClassAccess() {
		return (pPrimitiveClass != null) ? pPrimitiveClass : (pPrimitiveClass = new PrimitiveClassElements());
	}
	
	public ParserRule getPrimitiveClassRule() {
		return getPrimitiveClassAccess().getRule();
	}

	/// **
	// * descendants of GeneralClass
	// * / EmbeddedClass returns app::EmbeddedClass:
	//	"embedded" name=ID "{" "id" idProperty= //FIXME: reference???
	//	[app::EmbeddedProperty] embeddedProperties+=[app::EmbeddedProperty] embeddedProperties+=[app::EmbeddedProperty]* //FIXME: reference???
	//	"}";
	public EmbeddedClassElements getEmbeddedClassAccess() {
		return (pEmbeddedClass != null) ? pEmbeddedClass : (pEmbeddedClass = new EmbeddedClassElements());
	}
	
	public ParserRule getEmbeddedClassRule() {
		return getEmbeddedClassAccess().getRule();
	}

	//StandardClass returns app::StandardClass:
	//	isAbstract?="abstract"? "class" name=ID ("extends" parent=[app::StandardClass] "by" inheritanceType=InheritanceType)?
	//	"{" ("id" idProperty=[app::PrimitiveProperty])? //FIXME: reference???
	//	(properties+=MultipliableProperty properties+=MultipliableProperty*)? "}";
	public StandardClassElements getStandardClassAccess() {
		return (pStandardClass != null) ? pStandardClass : (pStandardClass = new StandardClassElements());
	}
	
	public ParserRule getStandardClassRule() {
		return getStandardClassAccess().getRule();
	}

	//Property returns app::Property:
	//	MultipliableProperty | EmbeddedProperty;
	public PropertyElements getPropertyAccess() {
		return (pProperty != null) ? pProperty : (pProperty = new PropertyElements());
	}
	
	public ParserRule getPropertyRule() {
		return getPropertyAccess().getRule();
	}

	//MultipliableProperty returns app::MultipliableProperty:
	//	AssociationProperty | PrimitiveProperty | NestedProperty;
	public MultipliablePropertyElements getMultipliablePropertyAccess() {
		return (pMultipliableProperty != null) ? pMultipliableProperty : (pMultipliableProperty = new MultipliablePropertyElements());
	}
	
	public ParserRule getMultipliablePropertyRule() {
		return getMultipliablePropertyAccess().getRule();
	}

	//EmbeddedProperty returns app::EmbeddedProperty:
	//	"EmbeddedProperty" isMandatory?="mandatory" name=ID ":" type=[app::PrimitiveClass];
	public EmbeddedPropertyElements getEmbeddedPropertyAccess() {
		return (pEmbeddedProperty != null) ? pEmbeddedProperty : (pEmbeddedProperty = new EmbeddedPropertyElements());
	}
	
	public ParserRule getEmbeddedPropertyRule() {
		return getEmbeddedPropertyAccess().getRule();
	}

	//PrimitiveProperty returns app::PrimitiveProperty:
	//	"PrimitiveProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
	//	upperBound=INT) "]")? ":" type=[app::PrimitiveClass] ("=" defaultValue=ID)?;
	public PrimitivePropertyElements getPrimitivePropertyAccess() {
		return (pPrimitiveProperty != null) ? pPrimitiveProperty : (pPrimitiveProperty = new PrimitivePropertyElements());
	}
	
	public ParserRule getPrimitivePropertyRule() {
		return getPrimitivePropertyAccess().getRule();
	}

	//AssociationProperty returns app::AssociationProperty:
	//	"AssociationProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
	//	upperBound=INT) "]")? ("oposite" oppositeProperty=[app::AssociationProperty])? ":" type=[app::StandardClass];
	public AssociationPropertyElements getAssociationPropertyAccess() {
		return (pAssociationProperty != null) ? pAssociationProperty : (pAssociationProperty = new AssociationPropertyElements());
	}
	
	public ParserRule getAssociationPropertyRule() {
		return getAssociationPropertyAccess().getRule();
	}

	//NestedProperty returns app::NestedProperty:
	//	"NestedProperty" (isOrdered?="ordered"? & isUnique?="unique"?) name=ID ("[" upperBound=INT | (lowerBound=INT ".."
	//	upperBound=INT) "]")? ":" type=[app::EmbeddedClass];
	public NestedPropertyElements getNestedPropertyAccess() {
		return (pNestedProperty != null) ? pNestedProperty : (pNestedProperty = new NestedPropertyElements());
	}
	
	public ParserRule getNestedPropertyRule() {
		return getNestedPropertyAccess().getRule();
	}

	//enum PrimitiveType returns app::PrimitiveType:
	//	boolean | char | int;
	public PrimitiveTypeElements getPrimitiveTypeAccess() {
		return (unknownRulePrimitiveType != null) ? unknownRulePrimitiveType : (unknownRulePrimitiveType = new PrimitiveTypeElements());
	}
	
	public EnumRule getPrimitiveTypeRule() {
		return getPrimitiveTypeAccess().getRule();
	}

	//enum InheritanceType returns app::InheritanceType:
	//	joined | tablePerClass | singleTable;
	public InheritanceTypeElements getInheritanceTypeAccess() {
		return (unknownRuleInheritanceType != null) ? unknownRuleInheritanceType : (unknownRuleInheritanceType = new InheritanceTypeElements());
	}
	
	public EnumRule getInheritanceTypeRule() {
		return getInheritanceTypeAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return (pEBoolean != null) ? pEBoolean : (pEBoolean = new EBooleanElements());
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//terminal ID:
	//	("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
