/*
 * generated by Xtext
 */
package migdb.dsl.app;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AppRuntimeModule extends migdb.dsl.app.AbstractAppRuntimeModule {

}
