<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mm"
    nsURI="http://www.collectionspro.eu/jam/mm" nsPrefix="mm">
  <eSubpackages name="errors" nsURI="http://www.collectionspro.eu/jam/mm/errors" nsPrefix="errors">
    <eClassifiers xsi:type="ecore:EClass" name="ErrorLog">
      <eStructuralFeatures xsi:type="ecore:EReference" name="errors" upperBound="-1"
          eType="#//errors/Error" containment="true" eOpposite="#//errors/Error/owningLog"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Error" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="message" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningLog" lowerBound="1"
          eType="#//errors/ErrorLog" changeable="false" derived="true" eOpposite="#//errors/ErrorLog/errors"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="transformationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValidationError" eSuperTypes="#//errors/Error"/>
    <eClassifiers xsi:type="ecore:EClass" name="EvolutionError" eSuperTypes="#//errors/Error">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OrmError" eSuperTypes="#//errors/Error"/>
  </eSubpackages>
</ecore:EPackage>
