/*
 * generated by Xtext
 */
package migdb.dsl.ops;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class OpsRuntimeModule extends migdb.dsl.ops.AbstractOpsRuntimeModule {

}
