/*
 * generated by Xtext
 */
package migdb.dsl.ops.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class OpsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return migdb.dsl.ops.ui.internal.OpsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return migdb.dsl.ops.ui.internal.OpsActivator.getInstance().getInjector("migdb.dsl.ops.Ops");
	}
	
}
