/*
* generated by Xtext
*/
package migdb.dsl.app.ui.contentassist;

import migdb.dsl.app.ui.contentassist.AbstractAppProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AppProposalProvider extends AbstractAppProposalProvider {

}
