<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mm"
    nsURI="http://www.collectionspro.eu/jam/mm" nsPrefix="mm">
  <eSubpackages name="sql" nsURI="http://www.collectionspro.eu/jam/mm/sql" nsPrefix="sql">
    <eClassifiers xsi:type="ecore:EClass" name="ModelRoot">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
          eType="#//sql/Statement" containment="true" eOpposite="#//sql/Statement/owningModelRoot"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Statement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningModelRoot" lowerBound="1"
          eType="#//sql/ModelRoot" changeable="false" derived="true" eOpposite="#//sql/ModelRoot/statements"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sqlCode" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
