/*
* generated by Xtext
*/
package migdb.dsl.ops.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class OpsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
